on: [push]

jobs:
  run_tests_job:
    runs-on: ubuntu-latest
    name: commit gate (tests)
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run testcases
        uses: ./.github/actions/run-tests
        id: run-tests

  run_linters_job:
    runs-on: ubuntu-latest
    name: commit gate (linters)
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run linters
        uses: ./.github/actions/run-linters
        id: run-linters

  build_model_job:
    runs-on: ubuntu-latest
    name: commit gate (build)
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build model
        uses: ./.github/actions/build-model
        id: build-model
